FROM public.ecr.aws/amazonlinux/amazonlinux:2023

##
## This Dockerfile is specifically designed to be run with the API Server
## and started via docker-compose. It makes assumptions about the existence
## of an docker internal network.
##

## wget is used to retrieve Conda and SysML Release. Inkscape and LaTeX is
## required for rendering notebooks as PDFs.
USER root
RUN dnf update -y 
RUN  dnf install -y -q \
    shadow-utils  \
    tar  \
    findutils   \
    gzip   \
    glibc   \
    wget  
#     libXrender  \
#     libXext    
RUN dnf clean all                       


##
## Non-root user is a requirement of Binder:
##   https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html
##
ARG NB_USER=sysml
ARG NB_UID=1000
ENV USER=${NB_USER}

ENV HOME=/home/${NB_USER}

RUN adduser \
    --uid ${NB_UID} \
    ${NB_USER}

USER root
RUN chown -R ${NB_UID} ${HOME}




## Switch to the lowly user, no more root.
USER ${NB_USER}
WORKDIR ${HOME}

##
## Miniconda installation page:
## https://docs.conda.io/en/latest/miniconda.html#linux-installers
##
RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh


COPY environment.yml .

## Install MiniConda
RUN chmod 755 ${HOME}/Miniconda3-latest-Linux-x86_64.sh
USER root
RUN mkdir /opt/conda
RUN ${HOME}/Miniconda3-latest-Linux-x86_64.sh -f -b -p /opt/conda
RUN /opt/conda/condabin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main \
 && /opt/conda/condabin/conda tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r

# RUN ${HOME}/conda/condabin/conda update -n base conda

# this is a replacement for conda init since it doesn't like to work in Dockerfiles
RUN set -x && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc && \
    find /opt/conda/ -follow -type f -name '*.a' -delete && \
    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
    /opt/conda/bin/conda clean -afy

## This is the path that conda init setups but conda init has no effect
ENV PATH="/opt/conda/bin:/opt/conda/condabin:${PATH}"
RUN conda env create -f environment.yml
SHELL ["conda", "run", "-n", "sysmlv2", "/bin/bash", "-c"]


# Make RUN commands use the new environment
# may not need these two commands
# RUN echo "conda activate sysmlv2" >> ~./bashrc
# SHELL ["/bin/bash", "--login", "-c"]

USER root
# RUN ${HOME}/conda/condabin/conda init bash
# RUN conda create -n sysmlv2
# RUN source activate sysmlv2
# RUN conda activate sysmlv2





## Install terminal notebook editor - https://github.com/joouha/euporie
# RUN pip install euporie
## Uninstall the terminal feature for security reasons
# RUN pip uninstall -y terminado
# RUN pip install pandas
# RUN pip install numpy
# RUN pip install matplotlib
# RUN pip install scipy

## Install SysMLv2 as Jupyter Kernel
ENV JUPYTER_ENABLE_LAB=yes
ENV JUPYTER_TOKEN=sysmlv2

# set env
# ENV NVM_DIR=${HOME}/.nvm
# ENV NODE_VERSION=20.19.6
# ENV NVM_SYMLINK_DIR=/usr/local/bin

# install node
# RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash 
# RUN source ${NVM_DIR}/nvm.sh
# ENV PATH=$NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH
# RUN source ~/.bashrc

## Defining the RELEASE down here ensures that the previous comamnds can
## be recycled since they're not affected by the release version.
ARG RELEASE=2025-12

##
## SysML page: https://github.com/Systems-Modeling/SysML-v2-Release
##
RUN wget -q https://github.com/Systems-Modeling/SysML-v2-Release/archive/${RELEASE}.tar.gz -O ${RELEASE}.tar.gz

USER ${NB_USER}

## Unpack SysML
RUN tar xzf ${RELEASE}.tar.gz

WORKDIR ${HOME}/SysML-v2-Release-${RELEASE}/install/jupyter

# Install SysMLv2 as Jupyter Kernel
WORKDIR ${HOME}/SysML-v2-Release-${RELEASE}/
ENV SYSML_VERSION=0.55.0

# RUN conda install "jupyter-sysml-kernel=$SYSML_VERSION" python=3.* jupyterlab=4.* graphviz=2.* nodejs=20.* -c conda-forge -y
USER root
RUN jupyter labextension install "@systems-modeling/jupyterlab-sysml@$SYSML_VERSION"
RUN python3 ./install/jupyter/install.py

## Point the publish command to the local API server.
RUN sed s/sysml2.intercax.com:9000/sysmlapiserver:9000/ -i /opt/conda/envs/sysmlv2/share/jupyter/kernels/sysml/kernel.json

## Move any files in the top level directory to the doc directory
RUN find . -maxdepth 1 -type f -exec mv \{\} doc \;

## Copy example notebooks into the image
RUN mkdir notebooks
COPY --chown=${NB_USER} notebooks/ notebooks/
COPY --chown=${NB_USER} jupyter_server_config.py .

COPY --chown=${NB_USER} jupyter_server_config.py ${HOME}/SysML-v2-Release-${RELEASE}


# Move some top level notebooks to the toplevel
RUN mv notebooks/*/StartHere.ipynb .
RUN mv notebooks/*.ipynb .

## Trust the notebooks so that the SVG images will be displayed.
RUN find . -name \*.ipynb -exec jupyter trust \{\} \;

# USER ${NB_USER}
RUN mkdir mydata
RUN chown ${NB_USER}:${NB_USER} mydata

USER root
COPY --chown=${NB_USER}:${NB_USER} entrypoint.sh .
RUN chmod 755 ./entrypoint.sh
EXPOSE 8888
# USER ${NB_USER}
# CMD ["tail", "-f", "/dev/null"]
# ENTRYPOINT jupyter lab --ip sysmljupyter --config ./jupyter_server_config.py
ENTRYPOINT ["./entrypoint.sh"]

